"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['SorcersDungeon.py']
DATA_FILES = [
    'Data'
]
OPTIONS = {
    'iconfile':'Data/Images/icon.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    name="Sorcer's Dungeon",
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
